// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJcDpx8Clh1z0VhEF1ZPT1HH2TMJgXZPs',
    appId: '1:666065892013:web:613ed4d2f71d33ce61cc24',
    messagingSenderId: '666065892013',
    projectId: 'music-services-app-693e7',
    authDomain: 'music-services-app-693e7.firebaseapp.com',
    storageBucket: 'music-services-app-693e7.firebasestorage.app',
    measurementId: 'G-T0YTR8THX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0NAG-09e6CIsg6aUk9ebbEfT-6xscsT8',
    appId: '1:666065892013:android:99e2a95e0d01cbcf61cc24',
    messagingSenderId: '666065892013',
    projectId: 'music-services-app-693e7',
    storageBucket: 'music-services-app-693e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdHMRRj8rVS3ENnfGFc-fBNflc7JSUyDI',
    appId: '1:666065892013:ios:67d09b1622f4b8d761cc24',
    messagingSenderId: '666065892013',
    projectId: 'music-services-app-693e7',
    storageBucket: 'music-services-app-693e7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdHMRRj8rVS3ENnfGFc-fBNflc7JSUyDI',
    appId: '1:666065892013:ios:67d09b1622f4b8d761cc24',
    messagingSenderId: '666065892013',
    projectId: 'music-services-app-693e7',
    storageBucket: 'music-services-app-693e7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication22',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJcDpx8Clh1z0VhEF1ZPT1HH2TMJgXZPs',
    appId: '1:666065892013:web:cd0b5b6664600df261cc24',
    messagingSenderId: '666065892013',
    projectId: 'music-services-app-693e7',
    authDomain: 'music-services-app-693e7.firebaseapp.com',
    storageBucket: 'music-services-app-693e7.firebasestorage.app',
    measurementId: 'G-WQBEHGPC58',
  );
}
